apiVersion: batch/v1
kind: Job
metadata:
  name: load-generator
spec:
  template:
    spec:
      containers:
      - name: load-generator
        image: ubuntu:latest
        command:
        - "/bin/sh"
        - "-c"
        - "while true; do curl -s http://10.32.12.54:80 & done"
      restartPolicy: Never
  backoffLimit: 4

