apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort  # 或 LoadBalancer/ClusterIP
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 32342

