apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: my-app  # 目标 Deployment 名称
  updatePolicy:
    updateMode: Auto  # 自动调整资源限制
  resourcePolicy:
    containerPolicies:
    - containerName: "*"  # 应用于所有容器
      minAllowed:
        cpu: "50m"
        memory: "64Mi"
      maxAllowed:
        cpu: "1"
        memory: "1Gi"

