apiVersion: apps/v1
kind: Deployment
metadata:
  name: low-priority-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: low-priority
  template:
    metadata:
      labels:
        app: low-priority
    spec:
      priorityClassName: priority-low
      containers:
        - name: low-container
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: "115000m"
              memory: "108Gi"
            limits:
              cpu: "115000m"
              memory: "108Gi"
