apiVersion: v1
kind: Pod
metadata:
  name: high-cpu-pod
spec:
  containers:
    - name: stress-container
      image: ubuntu:latest
      imagePullPolicy: IfNotPresent
      args:
        - "-cpus"
        - "4"  # 占满 4 核 CPU
      resources:
        requests:
          cpu: "3500m"  # 请求 3.5 核 CPU
          memory: "500Mi"
        limits:
          cpu: "4000m"  # 限制 4 核 CPU
          memory: "700Mi"

