apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-toleration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-toleration
  template:
    metadata:
      labels:
        app: no-toleration
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"

