apiVersion: apps/v1
kind: Deployment
metadata:
  name: toleration-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toleration
  template:
    metadata:
      labels:
        app: toleration
    spec:
      containers:
        - name: ubuntu
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "sleep infinity"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      tolerations:
        - key: "key1"
          operator: "Equal"
          value: "value1"
          effect: "NoSchedule"
