apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: zone
                    operator: In
                    values:
                      - zone2  # 只允许调度到 zone=zone1 的节点上
      containers:
        - name: my-app
          image: ubuntu:latest  # 轻量级基础镜像
          command: ["/bin/sh", "-c", "sleep infinity"]  # 让容器保持运行

